### ISSUE TITLE
Some messages lead to a crash

### ISSUE THREAD

**Issue by wazdra** [bkettle/message-book#3]
In particular, the message : "https://citymapper.com/directions?endcoord=51.250276,6.764559&endname=Position%20actuelle&endaddress=Golzheim&isCurrentLocation=1&referrer=citymapper-messages" makes the process crash.

**Comment by bkettle** [comment]
What does the crash message look like? I wonder if this is fixed with #4.

**Comment by microspino** [comment]
Tried right now. Works like a charm! THX for this nice tool and for #4 
FYI I'm on Ventura 13.6.3 (22G436) with Rust stable 1.76.0.
198 pages pdf generated with all the chats I had with my wife since 2021. 
Will be a sort-of-gift to her.
Many many thx.

**Comment by bkettle** [comment]
Awesome! Glad it could be useful!
